config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#delete'

  post '/books', to: 'books#add'
  delete '/books', to: 'books#delete'
  get '/books', to:'books#show'
  patch '/books', to: 'books#update'

  post '/home', to: 'books#search'
  get '/home',  to: 'books#index'

  post '/signup',  to: 'users#create'
  get '/signup',  to: 'users#new'

  get '/settings',  to: 'lists#new'
  delete '/settings', to: 'lists#delete'
  post '/settings',  to: 'lists#create'
  patch '/settings', to: 'lists#update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, :through => :lists
  has_many :lists


  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include BooksHelper
  include UsersHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    if !logged_in?
      redirect_to login_path
    else
      @user = current_user
      render 'home'
    end
  end

  def search
    if logged_in?
      @list_of_books = list_from_api params
      @user = current_user
      render 'home'
    end
  end

  def delete
    if logged_in?
      @user = current_user
      @desired_list = @user.lists.find_by(list_id: params[:list_id])
      @desired_list.books.find_by(api_id: params[:book_id]).destroy
      redirect_to books_path(list_id: params[:list_id])
    end
  end

  def show
    if logged_in?
      @user = current_user
      if params[:list_id].to_i <= @user.lists.count
        @user = current_user
        @desired_list = @user.lists.find_by(list_id: params[:list_id])
        @list_of_books = @desired_list.books.all
      else
        redirect_to home_path
      end
    else
      redirect_to login_path
    end
  end

  def add
    if logged_in?
      @user = current_user
      new_book = volume_from_api params[:books][:api_id]
      @user.lists.find_by(list_id: params[:list_id]).books.create( new_book.attributes )

      flash.now[:success] = "Book added to favorites"
      redirect_to books_path(list_id: params[:list_id])
    end
  end

  def update
    if logged_in?
      @user = current_user
      old_book = @user.lists.find_by(list_id: params[:lists][:old_list_id]).books.find_by(api_id: params[:lists][:book_id])
      old_book.destroy
      new_book = @user.lists.find_by(list_id: params[:new_list_id]).books.create(old_book.attributes)
      redirect_to books_path(list_id: params[:new_list_id])
    end
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    if logged_in?
      @user = current_user
      render 'new'
    else
      redirect_to login_path
    end
  end

  def create
    if logged_in?
      @user = current_user
      new_list = @user.lists.create(name: params[:lists][:name], list_id: @user.lists.count + 1 )
      redirect_to books_path(list_id: new_list.list_id)
    end
  end

  def delete
    if logged_in?
      @user = current_user
      @user.lists.find_by(list_id: params[:list_id]).destroy
      redirect_to settings_path
    end
  end

  def update
    if logged_in?
      @user = current_user
      @target_list = @user.lists.find_by( list_id: params[:list_id] )
      @target_list.name = params[:lists][:name]
      @target_list.save
      redirect_to books_path(list_id: params[:list_id])
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      user = current_user
      redirect_to home_path
    else
      render 'new'
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash.now[:success] = "Successfully signed in"
      log_in user
      redirect_to home_path
    else
      flash.now[:danger] = "Incorrect password/username"
      render 'new'
    end
  end

  def delete
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if logged_in?
      redirect_to home_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      initialize_list_user @user
      log_in @user
      flash[:success] = "Welcome to notSoGoodreads!"
      redirect_to home_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
require 'open-uri'

module BooksHelper

  def list_from_api(params)
    list = []
    url = "https://www.googleapis.com/books/v1/volumes?q="+params[:books][:q]
    data = JSON.parse(open(url).read)

    # puts data["items"][4][""]

    data["items"].each do |book|
      # puts book["volumeInfo"]["imageLinks"]["smallThumbnail"]

      single_book = Book.new(api_id: book["id"],
                       image_link: book["volumeInfo"]["imageLinks"]["smallThumbnail"],
                       title: book["volumeInfo"]["title"],
                       publishedDate: book["volumeInfo"]["publishedDate"],
                       description: book["volumeInfo"]["description"])
      if book["volumeInfo"]["authors"] != nil
        single_book.author = book["volumeInfo"]["authors"].join(', ')
      end

      if book["volumeInfo"]["industryIdentifiers"] != nil
        if book["volumeInfo"]["industryIdentifiers"][1] != nil
          single_book.ISBN = book["volumeInfo"]["industryIdentifiers"][1]["identifier"]
        else
          single_book.ISBN = book["volumeInfo"]["industryIdentifiers"][0]["identifier"]
        end
      end


      list << single_book
    end
    return list
  end

  def volume_from_api(api_id)
    url = "https://www.googleapis.com/books/v1/volumes/"+api_id
    book = JSON.parse(open(url).read)

    single_book = Book.new(api_id: book["id"],
                     image_link: book["volumeInfo"]["imageLinks"]["smallThumbnail"],
                     title: book["volumeInfo"]["title"],
                     publishedDate: book["volumeInfo"]["publishedDate"],
                     description: book["volumeInfo"]["description"])

    if book["volumeInfo"]["authors"] != nil
      single_book.author = book["volumeInfo"]["authors"].join(', ')
    end

    if book["volumeInfo"]["industryIdentifiers"] != nil
      if book["volumeInfo"]["industryIdentifiers"][1] != nil
        single_book.ISBN = book["volumeInfo"]["industryIdentifiers"][1]["identifier"]
      else
        single_book.ISBN = book["volumeInfo"]["industryIdentifiers"][0]["identifier"]
      end
    end
    single_book
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def initialize_list_user(user)
    @user.update_attribute(:list_count, 4)
    @user.lists.create(name: "Favorites", list_id: 1)
    @user.lists.create(name: "To-Read", list_id: 2)
    @user.lists.create(name: "Read", list_id: 3)
    @user.lists.create(name: "Reading", list_id: 4)
    @user.save
    @user
  end
end

app/views/books/_book.html.erb
<li class="list-group-item" id="book-<%= book.api_id %>">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag book.image_link, class: "img-responsive thumbnail"%>
    </div>
    <div class="col-md-8">
      <h2><%= link_to book.title, '#detailModal', :id => 'detail_link', "data-toggle" => "modal", 'data-target' => "#detailModal-"+book.api_id %></h2>
      <h4><%= book.author %></h4>
      <% if search %>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal-<%= book.api_id%>">Add to List</button>
      <% else %>
        <div class="row">
          <div class="col-md-1">
            <button type="button" class="btn btn-primary" id="update-book-btn" data-toggle="modal" data-target="#updateModal-<%= book.api_id%>">Move to List</button>
          </div>
          <div class="col-md-1">
            <%= button_to "Remove", books_path, method: :delete, params: { list_id: @desired_list.list_id, book_id: book.api_id },
                                                                           class: "btn btn-primary",
                                                                           id: "remove-book-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% if search %>
    <div class="modal fade" id="addModal-<%= book.api_id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Add to list?</h4>
          </div>
          <div class="modal-body">
            Add <strong><%= book.title %></strong> to which list?
            <%= form_for(:books, :url=>{:action=>"add", :controller=>"books"} ) do |f| %>
              <%= select_tag(:list_id, options_from_collection_for_select(@user.lists.all, :list_id, :name), class: "form-control" ) %>
              <%= f.hidden_field :api_id, :value => book.api_id %>
              <%= f.submit "Add", class:"btn btn-primary", id: "search-add-btn"%>
            <% end %>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" id="modal-close-btn">Close</button>
          </div>
        </div>
      </div>
    </div>

  <% else %>

    <div class="modal fade" id="updateModal-<%= book.api_id%>" tabindex="-1" role="dialog" aria-labelledby="updateBook">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Move to list?</h4>
          </div>
          <div class="modal-body">
            Move <strong><%= book.title %></strong> to which list?
            <%= form_for(:lists, url: books_path, method: :patch ) do |f| %>
              <%= select_tag(:new_list_id, options_from_collection_for_select(@user.lists.where.not(list_id: @desired_list.list_id), :list_id, :name),
                                                                              class: "form-control" ) %>
              <%= f.hidden_field :old_list_id, :value => @desired_list.list_id %>
              <%= f.hidden_field :book_id, :value => book.api_id %>
              <%= f.submit "Move", class:"btn btn-primary", id: "list-modal-btn"%>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="modal-close-btn">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="modal fade" id="detailModal-<%= book.api_id%>" tabindex="-1" role="dialog" aria-labelledby="detailBook">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modalBookTitle"><strong><%= book.title %></strong></h4>
        </div>
        <div class="modal-body">
          <strong>Authors:</strong> <%= book.author %>
          <br>
          <br>
          <strong>Publish date:</strong> <%= book.publishedDate %>
          <br>
          <br>
          <strong>Description:</strong><br> <%= book.description.html_safe if !book.description.nil? %>
          <br>
          <br>
          <strong>ISBN: </strong><%= book.ISBN%>
          <br>
          <br>
          <%= link_to 'Google Books', "https://www.googleapis.com/books/v1/volumes/%"+book.api_id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" id="modal-close-btn">Close</button>
        </div>
      </div>
    </div>
  </div>


</li>

app/views/books/home.html.erb
<% provide(:title, "Home") %>
<%= @user.email %>


<div class="container">
  <div class="row">

    <div class="col-lg-8 col-lg-offset-2">

      <%= form_for(:books, url: home_path) do |f| %>

        <%= f.label :search %>
        <%= f.text_field :q, class: "form-control"%>

        <%= f.submit "Search", class:"btn btn-primary"%>
      <% end %>

      <ul class="list-group">
        <% if @list_of_books != nil%>
          <%= render partial: 'book', collection: @list_of_books, locals: {search: true} %>
        <% end %>
      </ul>


    </div>

  </div>
</div>

app/views/books/show.html.erb
<h1>
  <strong>
    <%= @desired_list.name %>
  </strong>
</h1>

<ul class="list-group">
  <% if @list_of_books != nil%>
    <%= render partial: 'book', collection: @list_of_books, locals: {search: false} %>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "notSoGoodreads", root_path, class: "navbar-brand"%>
    </div>
    <% if logged_in? %>
      <u1 class="nav navbar-nav">
        <li class="active"><a href="/home">Home</a></li>
        <li><%= link_to 'Favorites', books_path(:list_id=>"1")%></li>
        <li><%= link_to 'Read', books_path(:list_id=>"3")%></li>
        <li><%= link_to 'Reading', books_path(:list_id=>"4")%></li>
        <li><%= link_to 'To-Read', books_path(:list_id=>"2")%></li>
        <% @user = current_user %>
        <% if @user.lists.count > 4 %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">More<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% @user.lists.where.not(list_id: 1..4).each do |list|%>
                  <li><%= link_to list.name, books_path(:list_id=>list.list_id)%></li>
                <% end %>
              </ul>
          </li>
        <% end %>
      </u1>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to '<span class="glyphicon glyphicon-cog"></span> Settings'.html_safe, settings_path %>
        </li>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-log-out"></span> Logout'.html_safe, logout_path, method: :delete %>
        </li>
      </ul>
    <% else %>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to '<span class="glyphicon glyphicon-user"></span> Signup'.html_safe, signup_path %>
      </li>
      <li>
        <%= link_to '<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, login_path%>
      </li>
    </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotSoGoodreads | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/new.html.erb
<h1>List Settings</h1>

<div class="container" id="settings-container">
  <div class="row">
    <div class="col-md-6">
      <h3>
        Create new list
      </h3>
      <%= form_for(:lists, url: settings_path, method: :post, html: { onsubmit: "return confirm('Add new list?');" } ) do |f| %>
        <%= f.label :name%>
        <%= f.text_field :name, class: "form-control"%>

        <%= f.submit "Create List", class:"btn btn-primary settings-btn", id: "create-list-btn"%>
      <% end %>
    </div>
  </div>

  <div class="row" id="settings-update-row">
    <div class="col-md-6">
      <h3>
        Update List Name
      </h3>
      <%= form_for(:lists, url: settings_path, method: :patch, html: { onsubmit: "return confirm('Rename list?');" } ) do |f| %>
        <%= select_tag(:list_id, options_from_collection_for_select(@user.lists.where.not(list_id: 1..4), :list_id, :name), class: "form-control" ) %>

        <%= f.label :name%>
        <%= f.text_field :name, class: "form-control"%>
        
        <%= f.submit "Rename", class:"btn btn-primary settings-btn", id: "update-list-btn"%>
      <% end %>
    </div>
  </div>

  <div class="row" id="settings-delete-row">
    <div class="col-md-6">
      <h3>
        Delete List
      </h3>
      <%= form_for(:lists, url: settings_path, method: :delete, html: { onsubmit: "return confirm('Delete list?');" } ) do |f| %>
        <%= select_tag(:list_id, options_from_collection_for_select(@user.lists.where.not(list_id: 1..4), :list_id, :name), class: "form-control" ) %>
        <%= f.submit "Delete", class:"btn btn-primary settings-btn", id: "delete-list-btn"%>
      <% end %>
    </div>
  </div>


</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_111search.html.erb
<div class="col-lg-8 col-lg-offset-2">

  <%= form_for(:books, :url => {:action=> "search", :controller => "users"}) do |f| %>

  <%= f.label :search %>
  <%= f.text_field :q, class: "form-control"%>

  <%= f.submit "Search", class:"btn btn-primary"%>
  <% end %>

  <ul class="list-group">
    <% if @list_of_books != nil%>
    <%= render @list_of_books%>
    <% end %>
  </ul>
</div>

app/views/users/_search.html.erb
<div class="col-lg-8 col-lg-offset-2">

  <%= form_for(:books, :url => {:action=> "search", :controller => "users"}) do |f| %>

  <%= f.label :search %>
  <%= f.text_field :q, class: "form-control"%>

  <%= f.submit "Search", class:"btn btn-primary"%>
  <% end %>

  <ul class="list-group">
    <% if @list_of_books != nil%>
    <%= render @list_of_books%>
    <% end %>
  </ul>
</div>

app/views/users/home.html.erb
<% provide(:title, "Home") %>
<%= @user.email %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Home") %>
<%= @user.email %>


<div class="container">
  <div class="row">

    <%= render "search" %>

  </div>
</div>